algoritmo "Flavio, INF221"
// Função :
// Autor :
// Data : 09/03/2024
// Seção de Declarações 
var
val, val2: inteiro
inicio

escreva("Insira o primeiro valor: ")
leia(val)

escreva("Insira o segundo valor: ")
leia(val2)

SE val > val2 ENTAO
   ESCREVAL("O valor ", val, " é maior que ", val2)
   fimalgoritmo
FIMSE

SE val2 > val ENTAO
   ESCREVAL("O valor ", val2, " é maior que ", val)
   fimalgoritmo
FIMSE

// Seção de Comandos 
fimalgoritmo
