algoritmo "Flavio, INF221"
// Função :
// Autor :
// Data : 01/03/2024
// Seção de Declarações 
var
compra: real
parcelas: inteiro
inicio
escreval("Insira o valor da compra.")
leia(compra)

escreval("Insira em quantas parcelas a compra será efetuada.")
leia(parcelas)

escreval("Do valor R$", compra, ", será R$", (compra/parcelas), " por mês (", parcelas, "x)")

// Seção de Comandos 
fimalgoritmo
